twig:
    default_path: '%kernel.project_dir%/templates'
    form_theme:
        - components/form.html.twig
    globals:
        configuration:
            payment: "%payment%"

when@test:
    twig:
        strict_variables: true
