parameters:
    fixture:
        path: '%kernel.project_dir%/data/fixtures'
    mailer:
        templateFolder: mail/
        senderAddress: noreply@music-one.com
        supportAddress: support@music-one.com
    media:
        repository: "%kernel.project_dir%/public/data"
        path: data/
    location:
        url: https://api.mapbox.com/geocoding/v5/
        token: "%env(MAPBOX_TOKEN)%"
    payment:
        publicKey: "%env(STRIPE_PUBLIC_KEY)%"
        privateKey: "%env(STRIPE_PRIVATE_KEY)%"
        currency : "eur"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Event\DoctrinePasswordHasher:
        tags:
            - name: 'doctrine.event_subscriber'